services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: no
    depends_on:
      - backend
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://divlog_dbuser:divlog123@db:5432/divlog?schema=public
    volumes:
      - ./backend:/app
      - /app/node_modules
  db:
    container_name: db
    image: postgres:latest
    restart: no
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}