version: "3.9"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://divlog_admin:divlog123@db:5432/divlog?schema=public
  db:
    container_name: db
    image: postgres:12
    restart: no
    environment:
      POSTGRES_USER: divlog_admin
      POSTGRES_PASSWORD: divlog123
      POSTGRES_DB: divlog
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}